import React, { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'

const DEMO_STEPS = [
  { type: 'cities', content: 'Seoul · Toronto' },
  { type: 'topic', icon: '🍂', name: 'Loss', question: 'What have you left behind that still travels with you?' },
  { type: 'answer1', text: '"Hotpot with my mom — I haven\'t found anything like it here"' },
  { type: 'answer2', text: '"The feeling of walking into my home church on a Sunday morning"' },
  { type: 'halfway', text: 'What if the hotpot and the Sunday morning are actually the same hunger — and neither of them is really what you\'re looking for?' },
]

const STEP_DURATIONS = [1800, 2400, 2800, 2800, 4500]
const STEP_BLOOMS = [
  'radial-gradient(ellipse 70% 50% at 50% 40%, rgba(212, 169, 106, 0.1) 0%, transparent 72%)',
  'radial-gradient(ellipse 70% 50% at 50% 45%, rgba(196, 98, 45, 0.1) 0%, transparent 72%)',
  'radial-gradient(ellipse 80% 55% at 40% 48%, rgba(196, 98, 45, 0.08) 0%, transparent 72%)',
  'radial-gradient(ellipse 80% 55% at 60% 48%, rgba(122, 158, 126, 0.1) 0%, transparent 72%)',
  'radial-gradient(ellipse 80% 60% at 50% 45%, rgba(212, 169, 106, 0.12) 0%, transparent 72%)',
]

export default function DemoLoop({ hasHistory, onStart, onHistory, onAtlas }) {
  const [step, setStep] = useState(0)

  useEffect(() => {
    const duration = STEP_DURATIONS[step] ?? 2000
    const timer = setTimeout(() => {
      const next = (step + 1) % DEMO_STEPS.length
      setStep(next)
    }, duration)
    return () => clearTimeout(timer)
  }, [step])

  const current = DEMO_STEPS[step]

  return (
    <div className="min-h-screen flex flex-col items-center justify-between px-6 py-16 max-w-md mx-auto">
      {/* Demo area */}
      <div className="relative flex-1 flex flex-col items-center justify-center w-full">
        <AnimatePresence mode="wait">
          <motion.div
            key={`bloom-${step}`}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.7 }}
            className="absolute inset-0 pointer-events-none"
            style={{ background: STEP_BLOOMS[step] }}
          />
        </AnimatePresence>
        <AnimatePresence mode="wait">
          <motion.div
            key={step}
            initial={{ opacity: 0, y: 14 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            transition={{ duration: 0.5 }}
            className="text-center w-full relative"
          >
            {current.type === 'cities' && (
              <p className="font-serif text-2xl text-brown-deep/40 tracking-wide">
                {current.content}
              </p>
            )}

            {current.type === 'topic' && (
              <div className="ink-card wash-sand p-6 text-center border border-sand/30">
                <p className="text-4xl mb-3">{current.icon}</p>
                <p className="font-serif text-xl font-bold text-brown-deep mb-2">{current.name}</p>
                <p className="font-serif italic text-brown-deep/60 text-base leading-relaxed">
                  {current.question}
                </p>
              </div>
            )}

            {current.type === 'answer1' && (
              <div className="ink-card wash-terracotta p-4 text-left border border-terracotta/20">
                <p className="text-[10px] uppercase tracking-widest text-terracotta/60 mb-2 font-semibold">Seoul</p>
                <p className="font-serif italic text-brown-deep/80 text-base leading-relaxed">{current.text}</p>
              </div>
            )}

            {current.type === 'answer2' && (
              <div className="ink-card wash-sage p-4 text-left border border-sage/20">
                <p className="text-[10px] uppercase tracking-widest text-sage/70 mb-2 font-semibold">Toronto</p>
                <p className="font-serif italic text-brown-deep/80 text-base leading-relaxed">{current.text}</p>
              </div>
            )}

            {current.type === 'halfway' && (
              <div className="space-y-4 py-4">
                <div className="w-8 h-px bg-terracotta/40 mx-auto" />
                <p className="text-[10px] font-semibold uppercase tracking-widest text-sand">✦ Halfway Question</p>
                <p className="font-serif italic text-brown-deep text-xl leading-relaxed">"{current.text}"</p>
                <p className="text-[10px] text-brown-deep/30 uppercase tracking-widest">Generated by AI</p>
              </div>
            )}
          </motion.div>
        </AnimatePresence>
      </div>

      {/* Brand + CTA */}
      <div className="w-full space-y-6 text-center">
        <div>
          <h1 className="font-serif text-5xl font-bold text-brown-deep">Halfway</h1>
          <p className="text-brown-deep/40 mt-2 text-sm italic font-serif">
            Where are you really from?
          </p>
          <p className="text-brown-deep/35 text-xs mt-3 tracking-wide">
            ✦ AI-powered · Both people answer · One question connects you
          </p>
        </div>

        <div className="space-y-3">
          <button
            onClick={onStart}
            className="w-full bg-brown-deep text-parchment py-4 rounded-2xl font-semibold text-base hover:bg-brown-deep/90 transition-colors"
          >
            Start a Conversation
          </button>

          {hasHistory && (
            <button
              onClick={onHistory}
              className="w-full text-brown-deep/50 py-2 text-sm hover:text-brown-deep transition-colors font-serif italic"
            >
              Past Conversations
            </button>
          )}
        </div>

        <button
          onClick={onAtlas}
          className="text-brown-deep/25 text-xs hover:text-brown-deep/50 transition-colors"
        >
          🌍 Atlas
        </button>
      </div>
    </div>
  )
}
